const eyesData = [
  { id: 1, name: 'Angry', url: '/src/assets/eyes/Angry.png' },
  { id: 2, name: 'Anime', url: '/src/assets/eyes/Anime.png' },
  { id: 3, name: 'Happy', url: '/src/assets/eyes/Happy.png' },
  { id: 4, name: 'Blue_eyes_with_shiner', url: '/src/assets/eyes/Blue_eyes_with_shiner.png' },
  { id: 5, name: 'Blue_eyes', url: '/src/assets/eyes/Blue_eyes.png' },
  { id: 6, name: 'Closed', url: '/src/assets/eyes/Closed.png' },
  { id: 7, name: 'Confused_with_glasses', url: '/src/assets/eyes/Confused_with_glasses.png' },
  { id: 8, name: 'Confused', url: '/src/assets/eyes/Confused.png' },
  { id: 9, name: 'Flirt', url: '/src/assets/eyes/Flirt.png' },
  { id: 10, name: 'Girl', url: '/src/assets/eyes/Girl.png' },
  { id: 11, name: 'Insomnia', url: '/src/assets/eyes/Insomnia.png' },
  { id: 12, name: 'Laugh', url: '/src/assets/eyes/Laugh.png' },
  { id: 13, name: 'Naruto', url: '/src/assets/eyes/Naruto.png' },
  { id: 14, name: 'Nervous', url: '/src/assets/eyes/Nervous.png' },
  { id: 15, name: 'Nuclear', url: '/src/assets/eyes/Nuclear.png' },
  { id: 16, name: 'Old', url: '/src/assets/eyes/Old.png' },
  { id: 17, name: 'Sad_Confused_with_glasses', url: '/src/assets/eyes/Sad_Confused_with_glasses.png' },
  { id: 18, name: 'Sad_Confused', url: '/src/assets/eyes/Sad_Confused.png' },
  { id: 19, name: 'Sad', url: '/src/assets/eyes/Sad.png' },
  { id: 20, name: 'Scared', url: '/src/assets/eyes/Scared.png' },
  { id: 21, name: 'Simple', url: '/src/assets/eyes/Simple.png' },
  { id: 22, name: 'Success', url: '/src/assets/eyes/Success.png' },
  { id: 23, name: 'Sunglasses', url: '/src/assets/eyes/Sunglasses.png' },
];

export { eyesData };